### ISSUE TITLE
openitcockpit/victoria-metrics 4.6.9 and 4.6.10 not startup 

### ISSUE THREAD

**Issue by KayRitzmann** [it-novum/openITCOCKPIT-ce-docker#6]
run.sh runs in error:

unprocessed command-line args left: %s; the most likely reason is missing `=` between boolean flag name and value; see https://pkg.go.dev/flag#hdr-Command_line_flag_syntax

there was breaking change in issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4845

Solution could be:

- delete run.sh
- change in compose.yaml:
```
victoria-metrics:
    image: openitcockpit/victoria-metrics:latest
    env_file:
     - openitcockpit.env
    command:
     - "--storageDataPath=/storage"
     - "--graphiteListenAddr=:2003"
     - "--opentsdbListenAddr=:4242"
     - "--httpListenAddr=:8428"
    ports:
      - "8428"       # victoria-metrics
    networks:
      - oitc-backend
    deploy:
      restart_policy:
        condition: on-failure
```
Or use same approach in container with entry point and cmd
